### ISSUE TITLE
Add ability to use blacklist as a whitelist

### ISSUE THREAD

**Issue by steve228uk** [steve228uk/QBlocker#1]
Currently all apps are blocked unless added to the exclusion this. This list should be changed to add the ability to use it as a blacklist or a whitelist.

**Comment by yuzhouwww** [comment]
Good idea! Are you working on this now?

**Comment by samtgarson** [comment]
+1

**Comment by Jyqft** [comment]
+1

**Comment by steve228uk** [comment]
Fixed in #14
