### ISSUE TITLE
Could not open the menu.

### ISSUE THREAD

**Issue by 0x0c** [steve228uk/QBlocker#13]
I cannot open the menu because when I click the menu on the menu bar, the app crashed.

My environment is the following.
- OSX 10.11.4
- Macbook Pro 15' Mid 2014
- QBlocker 1.0.2

**Comment by steve228uk** [comment]
Please see #4

**Comment by 0x0c** [comment]
Oh, sorry.

**Comment by steve228uk** [comment]
No problem, hopefully that fixes it 😊
