### ISSUE TITLE
QBlocker does not block anything (El Capitan 10.11.5)

### ISSUE THREAD

**Issue by christophberger** [steve228uk/QBlocker#18]
QBlocker 1.1 starts without issues and installs itself into the menu bar, but apart from that, it does not block any Cmd-Q for any app. All apps exit immediately. This is the first time I use QBlocker, I cannot tell whether previous versions would have worked.
How can I track down why QBlocker fails on my machine?

Edit: Forgot to add - Yes, I did enable QBlocker in the Accessibility settings as requested at first startup.

**Comment by steve228uk** [comment]
I'm not able to replicate this. Are you able to confirm the following:

- Your current keyboard layout
- Other apps open that also use accessibility settings
- Trying a past release from the Releases screen.

**Comment by christophberger** [comment]
* I use a German keyboard.
* BetterTouchTool, Dropbox, Google Software Update, Spectacle, Steam. I disabled them all and closed those that were running but this did not change anything. I even closed Chrome (which has its own Cmd-Q blocking) but this had no effect either.
* I tried all releases from 1.0 to 1.2 without luck. 
I know there must be something on my machine that blocks QBlocker but I have no idea what it is.

**Comment by steve228uk** [comment]
I've just switched my keyboard to a German QWERTZ layout and am not able to replicate this. Unfortunately it seems that something on your machine is blocking QBlocker from working. If you can work out the steps to reproduce please re-open this issue.

**Comment by christophberger** [comment]
This issue has been closed already, but for the curious reader: -

I thought the problem might be because my account has no admin rights. So I decided to test QBlocker with my admin account. Before that, I started QBlocker with my normal account...

...and it works like a charm.

I have absolutely no idea what changed between then and now. Anyway, looks like this was just some weird one-time glitch on my system.

**Comment by steve228uk** [comment]
Thanks for reporting back. I'll give it a try on a non-admin account.

**Comment by christophberger** [comment]
No, please don't waste your time! I cannot replicate the problem anymore.

What I meant to say in the previous post: Before testing with admin, I first tested again with my normal account to ensure the "bug" is still there but to my positive surprise it was gone. QBlocker now works as if there never was any problem. So there is nothing to replicate. The problem is gone and I hope it will be gone forever. QBlocker is such a useful tool that I wish I already had it when I switched from Windows PC to Mac!

**Comment by steve228uk** [comment]
👍
