### ISSUE TITLE
App crashes if click menu bar icon

### ISSUE THREAD

**Issue by ngocphamm** [steve228uk/QBlocker#4]
Every time for me.

System information
OS: 10.11.4
QBlocker version (from Cmd + I panel as I cannot click the menu bar icon): 1.0.1

**Comment by steve228uk** [comment]
@ngocphamm Are you able to check in your System Preferences -> User -> Login items if there's a login item there with a ⚠️ next to it?

**Comment by ngocphamm** [comment]
Wow. It's really it. I have one and as soon as I remove it, QBlocker menu bar icon works again! Thank you!

**Comment by steve228uk** [comment]
@ngocphamm No problem! It's an OS X issue and not sure of a work around 😟 Thanks for letting me know! Probably should add an FAQ section really.
