### ISSUE TITLE
Exclude app window does not come to foreground

### ISSUE THREAD

**Issue by ngocphamm** [steve228uk/QBlocker#5]
After having the menu bar working again (thank you @steve228uk), I found out that the pop up for excluding apps will not come to foreground. I wonder if there can be a simple fix.

**Comment by steve228uk** [comment]
Thanks for reporting this @ngocphamm! I did try to resolve this with https://github.com/steve228uk/QBlocker/blob/master/QBlocker/ExcludeWindowController.swift#L16-L17 and thought it had fixed the issue though it seems not.

**Comment by luiyezheng** [comment]
I found If I "check for update" first, then the pop up for excluding apps will come to foreground.as expected.

**Comment by steve228uk** [comment]
Fixed in #14
